version: "3"
services:
  ngingx:
    image: nginx:latest
    container_name: nginx
    # build: ./nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi

  fastapi:
    image: isan19973788/fastapi
    # build:
    #   dockerfile: Dockerfile
    container_name: fastapi
    # command:
    #   - uvicorn
    #   - main:app
    #   - --bind
    #   - 0.0.0.0:8000
    restart: always
    volumes:
      - ./app:/app
    # expose:
    #   - "8000"
    ports:
      - 8000:8000
