version: "3"
services:
  ngingx:
    image: isan19973788/nginx
    container_name: nginx
    # build: ./nginx
    ports:
      - 81:81
    restart: always
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi
    networks:
      - web-network

  fastapi:
    image: isan19973788/fastapi
    # build:
    #   dockerfile: Dockerfile
    container_name: fastapi
    restart: always
    # volumes:
    #   - ./app:/app
    # expose:
    #   - "8000"
    ports:
      - 8000:8000
    networks:
      - web-network
  
networks:
  web-network:
    driver: bridge